title: Veterans Preference Interactive Guide
description: An interactive guide to understanding Veterans' Preference in federal hiring.
theme: jekyll-theme-minimal
url: "" # Your GitHub Pages URL
baseurl: "" # Usually empty for project pages, or /repo-name for user/org pages

# Optional: Add default front matter for pages/collections
defaults:
  - scope:
      path: ""
      type: "pages" # This will apply to all .md files that are not posts or in collections
    values:
      layout: "page"
  - scope:
      path: ""
      type: "appendices" # Assuming 'appendices' is the collection name
    values:
      layout: "collection_item"
      # Add other defaults like category if needed

# Collections setup
collections:
  appendices:
    output: true
    permalink: /appendices/:name/
